name: ai_personal_assistant
description: An AI-powered voice assistant using Flutter, GPT, TTS, and Whisper.
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # HTTP/API
  dio: ^5.4.1
  http: ^1.2.1

  # Local Storage & DB
  drift: ^2.16.0
  drift_flutter: ^2.16.0
  path_provider: ^2.1.3
  sqlite3_flutter_libs: ^0.5.15

  # STT & TTS
  speech_to_text: ^6.4.0
  flutter_tts: ^5.0.4

  # Permissions
  permission_handler: ^11.3.0

  # Platform Channels & FFI
  ffi: ^2.1.2

  # UI
  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.5.1
  google_fonts: ^6.1.0

  # JSON Serialization
  json_annotation: ^4.9.0

  # Assets / Sound
  audioplayers: ^5.2.1

  # Device Info (for personalization, etc.)
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  build_runner: ^2.4.7
  json_serializable: ^6.8.0
  drift_dev: ^2.16.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/sounds/
    - assets/prompts/persona_templates/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
